# 加入服务器时要传送的坐标。
cords:
  x: 0
  y: 100
  z: 0

#加入服务器时要发送的消息，支持换行。
joinMessage: "Hi，欢迎来到服务器"
#玩家加入服务器多少次后停止发送消息；
#设置为0则始终发送消息；设置为负数则关闭该功能；设置为正数则按照正常进行计数；
#例如：设置为15，当玩家第16次加入时不再向玩家发送消息。
stopMessagingTime: 15
